meta_product_name: "Clarify"
meta_title: "Clarify - Clear up skincare science and your skin"
meta_description: "Make sense of confusing ingredient lists in cosmetics by scanning a barcode, or search our extensive database to find the best product for you."
meta_image: "skincare.png" # should exist in `app/assets/images/`
